package com.example.zero.inclass11.fragments;

/**
 * @author Josiah Laivins
 * @version 10/23/2017
 */

public enum FragmentAction {

    FROM_LOGIN_GO_TO_SIGNUP,
    FROM_LOGIN_GO_TO_HOME,
    FROM_SIGN_UP_GO_TO_LOGIN,
    FROM_CANCEL_GO_TO_LOGIN,




    FROM_LOGOUT_GO_TO_LOGIN,
    FROM_CONTACTS_GO_TO_CREATE_CONTACT,
    FROM_CONTACTS_GO_TO_EDIT_OWN_CONTACT,
    FROM_CONTACTS_GO_TO_EDIT_CONTACT,

    FROM_CANCEL_CONTACT_GO_TO_CONTACTS,

    FROM_CREATE_CONTACT_GO_TO_SUBMIT_CONTACT,

    FROM_EDIT_OWN_CONTACT_GO_TO_SUBMIT_CONTACTS,
    FROM_EDIT_CONTACT_GO_TO_SUBMIT_CONTACTS,

}